server:
  port: 9080

spring:
  application:
    name: specification

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_example
    username: user
    password: pass
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

# API URLs for different environments
api:
  dev:
    url: http://localhost:9090

springdoc:
  #  api-docs:
  #    path: /v3/api-docs
  #    version: openapi_3_0
  swagger-ui:
    #    path: /swagger-ui.html
    #    enabled: true
    default-models-expand-depth: -1
